### ISSUE TITLE
Seagulls from Alex's Mobs steal and eat Lunchboxes

### ISSUE THREAD

**Issue by Gantros** [CreativeMD/Spice-of-Life-Onion#10]
I  had a Gold Lunchbox full of prepped Farmer's Delight meals, and a damn seagull snatched and ate the whole thing, box and all. I would think that they wouldn't be able to snatch the boxes from the hotbar.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I tried to find information about seagulls in this mod, but it seems like they take any item. If that is the case I do not see a reason why it should be excluded. Maybe you know more?

**Comment by Gantros** [comment]
They are supposed to take any single food item from your hotbar, so they wouldn't take a whole stack of something. With your lunch boxes, they can take stacks and stacks of high level foods, wasting them. being able to eat from the bag without fearing this scenario. For realism purposes, the paper bag could be snatched, but iron and gold lunchboxes shouldn't be able to be taken.

**Comment by CreativeMD** [comment]
I will contact the author and ask if this can be supported somehow.

**Comment by MysticcWaters** [comment]
Hey, just wanted to jump into this issue to say that Alex's Mobs actually does have a blacklist for items that the Seagull will take in its config (alexsmobs.toml). It should be labelled seagullStealingBlacklist. I tested this with Spice of Life's boxes and it worked just fine.

**Comment by CreativeMD** [comment]
Alright. @MysticcFibrosis thanks for letting us know. I will close the issue. Unfortunately I don't think there is an easy way to add it by default.
