### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by chessMCman** [CreativeMD/Spice-of-Life-Onion#11]
Just as I finished eating bread, I was killed by Creeper's explosion and the server crashed. The server crash log is as follows
[crash-2023-12-24_23.24.40-server.txt](https://github.com/CreativeMD/Spice-of-Life-Onion/files/13765974/crash-2023-12-24_23.24.40-server.txt)

**Comment by CreativeMD** [comment]
Does it happen every time you eat something? Have not seen this issue on a forge server. Maybe it is an issue of mohist?

**Comment by chessMCman** [comment]
No, it was because it was killed by Creeper's explosion at the time

**Comment by CreativeMD** [comment]
Ok, I implemented an extra check which should prevent the crash from occurring again. Still, this should not happen in the first place, so not sure if that issue is related to mohist or not. I will close the issue for now. If the issue persists just reply here and I will reopen it.
