### ISSUE TITLE
LunchBox doesn't support AppleSkin Preview and shows permanent Diversity 0

### ISSUE THREAD

**Issue by Ghostipedia** [CreativeMD/Spice-of-Life-Onion#12]
As stated on the tin, the lunchbox from SOL:Onion does not display the consumption preview of the food about to be consumed.
This feature used to be in older versions and made the lunchbox very viable.

I'm also observing that the "Diversity" of the lunchbox is always 0. This also seems like a bug, but I'm unsure if it's related or needs to be a separate issue

Due to this, it makes it very difficult for the player to understand what they're about to eat and eat without being wasteful.

An Example Video has been attached of the issues mentioned.
https://www.youtube.com/watch?v=1YRRmHkSi0w

**Comment by CreativeMD** [comment]
Hey sorry, I must have overlooked this issue somehow. This has been fixed in March. I hope the current version works for you. If not just respond here, I will be faster to respond this time (still I will close this issue for now as I think this has been resolved).
