### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Rogenar** [CreativeMD/Spice-of-Life-Onion#13]
I'm having a mod conflict can you help me?
[debug.log](https://github.com/CreativeMD/Spice-of-Life-Onion/files/13875448/debug.log)
I couldn't find which mode was causing the problem.
[latest.log](https://github.com/CreativeMD/Spice-of-Life-Onion/files/13875456/latest.log)

**Comment by CreativeMD** [comment]
Looks like you need to update fabric. It does not have anything to do with Spice of Life Onion as far as I can tell.
