### ISSUE TITLE
Apply for production support for version 1.19.2

### ISSUE THREAD

**Issue by Windavilin** [CreativeMD/Spice-of-Life-Onion#14]
Thank you very much for creating the Spice of Life Onion, which allows me to play both player rescue and the Spice of Life Potato branch simultaneously.

But I mainly play Minecraft version 1.19.2. Could you make a corresponding version for it?

**Comment by CreativeMD** [comment]
Sorry, but I do not support 1.19.2 anymore. You will have to update in order to use Spice of Life Onion.
