### ISSUE TITLE
Milk bucket clears infinite effects

### ISSUE THREAD

**Issue by bbgott** [CreativeMD/Spice-of-Life-Onion#15]
It seems that drinking milk from a bucket will clear earned player buffs until they eat their next food item.  Drinking a farmer's delight milk bottle will also clear a random buff that should be infinite.

MC: 1.20.1
Forge: 47.2.0
SOL: 1.2.2

**Comment by CreativeMD** [comment]
Fixed this issue in the newest version. Thanks for reporting this issue. Sorry for responding insanely late.
