### ISSUE TITLE
Lunchboxes/Lunch Bag conflict with Origins (Forge)

### ISSUE THREAD

**Issue by Kingdemonic666** [CreativeMD/Spice-of-Life-Onion#16]
Mods used:

caelus-forge-3.1.0+1.20.jar
CreativeCore_FORGE_v2.11.25_mc1.20.1.jar
origins-forge-1.20.1-1.10.0.7-all.jar
Patchouli-1.20.1-84-FORGE.jar
Placebo-1.20.1-8.6.1.jar
SoLOnion_FORGE_v1.2.3_mc1.20.1.jar

Forge version - 47.2.0

Expected Behavior
The lunchbox/lunch bag should be able to be eaten by any Origin not restricted by diet.

Actual Behavior
Lunchboxes and the Lunch Bag cannot be eaten when the Origins (Forge) Mod is present, regardless of the Origin selected by the player.

Other information:
The AlwaysEat mod by suppergerrie2 will bypass this issue and allow to forcefully eat the Lunchbox/Lunch Bag even when empty. However, this introduces another conflict of it's own, which is being unable to open the Lunchbox/Lunch Bag inventory under any circumstance.

**Comment by CreativeMD** [comment]
Currently working on a fix here: https://github.com/EdwinMindcraft/origins-architectury/issues/435
Let's hope it will be resolved soon.

**Comment by ChrysanthCow** [comment]
Potentially resolved by #21
