### ISSUE TITLE
crash on newest update

### ISSUE THREAD

**Issue by GreenForzeGaming** [CreativeMD/Spice-of-Life-Onion#17]
newest version crashes my game
[crash-2024-04-20_14.47.26-client (1).txt](https://github.com/CreativeMD/Spice-of-Life-Onion/files/15049135/crash-2024-04-20_14.47.26-client.1.txt)

**Comment by GreenForzeGaming** [comment]
its so frustrating when stuff like this happens. i didnt even know the milk was an issue at first and now people gets kicked out from game when certan items are aquierd.

**Comment by CreativeMD** [comment]
Oh right, thanks for reporting this issue. Released a new version which fixes it.
