### ISSUE TITLE
[Bug 1.20.4 NeoForge] Lunchbox Items Void Contents

### ISSUE THREAD

**Issue by HalestormXV** [CreativeMD/Spice-of-Life-Onion#19]
Adding any food item to any of the lunchbox items will destroy/void the item and then it is gone. The item gets adds or the items get added and once you close the Lunchbox Item out and reopen it all of the items are obliterated. Seems like the data isnt saving in the handler perhaps? 

NeoForge 20.4.232
Minecraft 1.20.4
modernFix 5.17.0+mc1.20.4

I have a variety of others mods in the pack but I don't see how any of them might conflict. 
https://modrinth.com/modpack/journey-beyond/version/1.0.3

Everything else in the mod seems to be working as intended. The only issue I have come across so far is the Lunchbox items.

**Comment by Saereth** [comment]
Can confirm this is still an issue with even a very minimal mod list, it's not saving the contents of the container once you close it, just voids all the food.

**Comment by bo-jensen** [comment]
This is also happening in the FTB NeoTech modpack

**Comment by CreativeMD** [comment]
Is this a thing in 1.21? Also sorry for not responding earlier.

**Comment by Saereth** [comment]
I can confirm this is an issue on 1.21 and 1.20.4 both currently with the latest builds of SOL Onion avaialble on CF for both

**Comment by CreativeMD** [comment]
Finally got around to fix this issue. Thank you very much for reporting this issue. Sorry for all the trouble!
