### ISSUE TITLE
Crash Level Incompatibility with Mana and Artifice

### ISSUE THREAD

**Issue by ViewPointGames** [CreativeMD/Spice-of-Life-Onion#20]
Hello!
I get a client crash to desktop when I tried to cast a wall-break spell from Mana and Artifice on some blocks. This created the drop entities as usual, but something about those entities was not making my client happy, thus leading to this crash report. The server seems to be able to handle this function, however I still lose the window.

Installations:
Minecraft 1.20.1
SoLO 1.2.4
Mana and Artifice 3.0.0.12

Steps to reproduce:
Create new world
enter commands `/mna progression tier @s 5` and `/mna progression rote all`
grab Book of Rote from creative inventory
create a wall - break spell with any parameters
cast spell

This is the crash report I received immediately after:
https://pastebin.com/9QyTAjFa

A few days later I had another error, likely similar to this one as the exception gets thrown seemingly at the same position, so I included this here too: This error is caused by drinking milk while having some diet effect active (idk which ones though sadly, but it was the default config):
https://pastebin.com/JLjgcYp2

Additional info:
Both of these pastes will be burned upon opening, so if you need to review this more than once, just message me.

**Comment by CreativeMD** [comment]
Sorry it took me way too long to respond. Very sorry. Unfortunately I cannot see the crash-report anymore. Can you post them again maybe? Is this actually still an issue?

**Comment by ViewPointGames** [comment]
Sadly no, I recently migrated my entire PC and the crash files did not transfer over.
However, I tried the reproductive steps out again, and they did not seem to cause a problem anymore.
A few weeks after this report was posted you released a new version, and I assume that one fixed the problem?

**Comment by CreativeMD** [comment]
Maybe. I mean these are actually good news. I will close this for now. If it happens again just let me know here. Thanks for spending the time to report this issue!
