### ISSUE TITLE
Candlelight Foods in Golden Lunch box Crash

### ISSUE THREAD

**Issue by Trixitania** [CreativeMD/Spice-of-Life-Onion#22]
When [Lets Do] Candlelight foods are added to the Golden Lunch box, and then you eat from the lunch box (in the "eat the lunchbox itself" way) you are kicked from the game/crashed. Has been replicated consistently. Any Candlelight foods its seems cant be eaten from the gold lunchbox. The paper bag and the Iron lunchbox seem to be ok :) (no crashes that Iv encountered)

Just tried to find my latest crash report from the issue, but it seems as though it doesn't count as a crash. Curseforge didnt pop up the "Crash" window either when it happened. Have included the latest log in case that helps!

Thankyou for such a lovely mod! Hope this helps some!

[latest.log](https://github.com/CreativeMD/Spice-of-Life-Onion/files/15287432/latest.log)

**Comment by CreativeMD** [comment]
Hey, unfortunately the latest.log does not contain any crash. Are you kicked from a server? If yes I would need the log file of the server. Without the error I cannot really see what is going wrong.

**Comment by Trixitania** [comment]
Its not a server kick I dont think. Im playing on a server hosted by someone using SOL in their modpack, and when you try and eat a piece of "Lets do! Candlelight" food from the gold lunchbox its not a crash, or a kick, its like the game was never open. It just -boom- closes. No crash report. No going back to the main menu. Its as though you were never running minecraft at all. Just closes. 

I shall poke the person who runs the server and ask for the logs :) thankyou for the reply!

**Comment by CreativeMD** [comment]
There is also a different way minecraft can crash, that is if Java itself crashes. In that case you can find `hs_err_pid`<number>.log` files in your minecraft directory. Do you have some of these? If yes can you send them to me?

Also sorry for responding quite late.

**Comment by CreativeMD** [comment]
Will close this due to inactivity. If there is more information just post it here.
