### ISSUE TITLE
Conflict problem with "AlwaysEat" MOD

### ISSUE THREAD

**Issue by Tooooomo** [CreativeMD/Spice-of-Life-Onion#23]
Hello!
I was considering installing some mods, including this one, on a server where I play with my friends. 
However, when I installed "AlwaysEat" at the same time as this mod, the feature disabled the shift + right click on the lunchbox and lunchbag, and prevented the GUI from opening.
I tried putting the lunchbox in the blacklist of the AlwaysEat config, but the lunchbox just became a box.

I will write down each version so that it can be used for verification.
Forge - 47.2.30
CreativeCore - CreativeCore_FORGE_v2.11.28_mc1.20.1
Spice of Life Onion - SoLOnion_FORGE_v1.2.7_mc1.20.1
AlwaysEat - alwayseat-5.2-1.19.2-1.20.1

If you could add a key config to open the lunchbox GUI, this problem would be solved.
This is a very limited case, but I would appreciate it if you could address this issue.

Finally, as a Spice of Life fan, I would like to thank you for your efforts in developing this wonderful mod. 
Sorry if my English is not good enough.

**Comment by CreativeMD** [comment]
Hey, thanks for your detailed description. Would it be possible to report this issue to AlwaysEat and link the issue here? I will join the conversation. Don't think it is an issue of Spice of Life itself.

**Comment by Tooooomo** [comment]
Sorry for the late reply!

I opened a similar issue in the AlwaysEat repository. Thanks for your response.
suppergerrie2/AlwaysEat#3

**Comment by CreativeMD** [comment]
Alright. I will keep an eye on it. Let's see how the author responds. I will close this issue here for now as it is not an issue of my mod itself.
