### ISSUE TITLE
Neoforge 1.20.4 Mod isnt incrimenting food count

### ISSUE THREAD

**Issue by Saereth** [CreativeMD/Spice-of-Life-Onion#24]
Running a stripped down pack for testing just JEI, Sol Onion and Pam's mods, no foods are counting towards being eaten including vanilla foods. I set the minimum food to 4 and it always says I need to eat 4 foods to see benefits. My diversity is also not increasing at all. 

Neoforge 20.4.234
MC: 1.20.4

Full modlist:
```
CreativeCore_NEOFORGE_v2.11.26_mc1.20.4
Spice of Life Onion_NEOFORGE_v1.2.5_mc1.20.4
pamhc2crops-NeoForge-1.20.4-1.0.4
pamhc2foodcore-NeoForge-1.20.4-1.0.7
pamhc2trees-NeoForge-1.20.4-1.0.3
modernfix-neoforge-5.17.0+mc1.20.4
ferritecore-6.0.3-forge
Jade-1.20.4-neoforge-13.3.1
AttributeFix-NeoForge-1.20.4-24.0.2
architectury-11.1.17-neoforge
cloth-config-13.0.121-neoforge
```

<img width="758" alt="image" src="https://github.com/CreativeMD/Spice-of-Life-Onion/assets/9200909/7d1ec34d-0913-4e83-ad0b-b40aa428e32a">

**Comment by CreativeMD** [comment]
Is it possible for you to update to 1.20.6? I kinda abandoned 1.20.4 already. There was an issue, which is fixed in the newest version for 1.20.6.

**Comment by Saereth** [comment]
Sadly no, the pack has been in dev for about 3 months and is nearing release, not even half of the mods have ported to 1.20.6 and several are waiting for 1.21+. If you are dropping support for 1.20.4 though I understand and you can close the issue, I appreciate the work on the mod regardless and will look forward to using it in future versions!

**Comment by CreativeMD** [comment]
Ported back the changes to 1.20.4. I don't really support it anymore, but I guess a small fix won't hurt. I hope it works now.

**Comment by Saereth** [comment]
Appreciate the fixes!, it appears the neoforge.mods.toml is still set to use the 1.20.6 mc and neoforge build 20.6.x instead of 1.20.4 and 20.4.x, I assume this was just an overwrite issue when merging or something simple. I checked in the actual jar as well to verify that was reason for it not currently loading using the latest version on CF (v1.2.6-1.20.4)

**Comment by CreativeMD** [comment]
Uploaded a new version which fixes it. Sorry for the trouble. I was also quite busy, that's why it took me so long.

**Comment by Saereth** [comment]
aawesome ty!
