### ISSUE TITLE
Server Crash - Player with no benefit capability

### ISSUE THREAD

**Issue by Dweblenod** [CreativeMD/Spice-of-Life-Onion#27]
Running a modded Minecraft server and encountered a server crash seemingly from when Iron's Spellbooks Vex spell ended.

### Seemingly relevant issue in Onion
A similar kind of check might work well!
- https://github.com/CreativeMD/Spice-of-Life-Onion/issues/11
- https://github.com/CreativeMD/Spice-of-Life-Onion/commit/398880f5d36b371d8a7c3e492ec26f9b70a763be

### Relevant code in Iron's. 
Line 70 is what is referenced in the crash report.
- https://github.com/iron431/irons-spells-n-spellbooks/blob/1.20.1/src/main/java/io/redspace/ironsspellbooks/entity/mobs/MagicSummon.java

### Crash Report
[crash-2024-08-07_17.06.00-server.txt](https://github.com/user-attachments/files/16535468/crash-2024-08-07_17.06.00-server.txt)

**Comment by CreativeMD** [comment]
Should be fixed in the newest version.
