### ISSUE TITLE
Allow All Food Containers (Lunch Sack, etc) to Refresh Contents

### ISSUE THREAD

**Issue by Danekjovax** [CreativeMD/Spice-of-Life-Onion#30]
Great new implementation of one of my favorite mods!  However...

I believe the older version of SoL allowed the player to refresh the contents of their Lunch Sack, etc to carry only the most beneficial foods when they shift-right-clicked a target inventory with the food container in-hand.  Could you add this feature to this version, please?

This feature would make these containers much more useful, and the player would only have to make a food chest and let the feature grab the best foods for them and minimize micromanagement of food items.  A win-win!

Thanks!

**Comment by CreativeMD** [comment]
Added in the newest version for 1.21. Thanks a lot for suggesting this feature.
