### ISSUE TITLE
1.20.1 client crash

### ISSUE THREAD

**Issue by zeRan404** [CreativeMD/Spice-of-Life-Onion#33]
1、use /cmdconfig
2、click the [add] button for [foodItems]
3、client crash

[crash-2024-10-29_12.38.19-client.txt](https://github.com/user-attachments/files/17551867/crash-2024-10-29_12.38.19-client.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore. Thanks for reporting this issue!
