### ISSUE TITLE
Game crashes with modpack, error with CreativeCore 1.20.1

### ISSUE THREAD

**Issue by bncripe** [CreativeMD/Spice-of-Life-Onion#34]
crash report: [crash-2024-11-16_23.37.00-fml.txt](https://github.com/user-attachments/files/17788965/crash-2024-11-16_23.37.00-fml.txt)

Whenever I try to open the game after adding SoL Onion, it crashes. I also tried the latest version of both CreativeCore and SoL Onion, but that crash wouldn't generate a crash report. When I made a new profile with just these two mods, the game worked fine.

I'm not sure what to do to make this work.

![image (2)](https://github.com/user-attachments/assets/80ae9ccd-beed-415f-a1c3-10f544218fc2)

**Comment by CreativeMD** [comment]
Please update CreativeCore. Sorry for not responding earlier.
