### ISSUE TITLE
[1.21.1] Crash on Eating after re-adding SOL

### ISSUE THREAD

**Issue by Flexico** [CreativeMD/Spice-of-Life-Onion#35]
I've been having some trouble with the Farmer's Delight food diversity numbers being ridiculously high (I left a comment on the CurseForge page), but after loading my world without SOL installed, then re-adding the mod and trying to eat something, the whole game immediately crashed.

NeoForge 21.1.80
Spice of Life Onion 1.4.5
[latest.log](https://github.com/user-attachments/files/17891547/latest.log)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for reporting this issue!
