### ISSUE TITLE
Incompatible with Origins (Forge)

### ISSUE THREAD

**Issue by ToryXie** [CreativeMD/Spice-of-Life-Onion#5]
Hello,
I put this mod and [Origins(Forge)](https://modrinth.com/mod/origins-forge) together, and lunchbox, lunchbag, golden lunchbox doesn't work.
# Mods Version Information
| Mod name | Version |
| :---: | :---: |
| Spice-of-Life-Onion&emsp | mc1.20.1-1.1.2 |
| CreativeCore | mc1.20.1-2.11.2 | 
| caelus | mc1.20.1-3.1.0 |
| Origins(Forge) | mc1.20.1-1.10.0.2 |
# Expected Behavior
Eating when lunchbag, lunchbox and golden lunchbox have food inside.
# Actual Behavior
It doesn't work.
# Other information
Forge version - 47.2.0

**Comment by CreativeMD** [comment]
I have looked at the code and I do not see a way to fix it from my end. Seems like this mod might struggle to support modded food. You should report it to them, maybe they can figure what is wrong and fix it. Feel free to provide the link here, I will join the conversation.
