### ISSUE TITLE
[NeoForge] Missing language features.

### ISSUE THREAD

**Issue by NanoAi** [CreativeMD/Spice-of-Life-Onion#7]
## Expected
Being able to see the results of commands such as `/solonion diversity`.
## Result
A tag that should display the text is shown but no information is displayed.
![image](https://github.com/CreativeMD/Spice-of-Life-Onion/assets/3096584/fc44e5c5-880f-400a-ae61-be003e28806c)
 
ATLauncher Version: 3.4.34.2
Mod Version: SoLOnion_FORGE_v1.1.3_mc1.20.1
Minecraft Version: 1.20.1
Forge (NeoForged): 47.1.79

**Comment by CreativeMD** [comment]
Fixed it in the newest version. Thanks for reporting this issue!
