### ISSUE TITLE
[Request] Add values from `anthxnymc/Spice-of-Life-Apple-Pie`

### ISSUE THREAD

**Issue by NanoAi** [CreativeMD/Spice-of-Life-Onion#8]
Please add the values from https://github.com/anthxnymc/Spice-of-Life-Apple-Pie/tree/1.20.1 as an optional configuration. In theory this should provide better mod support.

**Comment by CreativeMD** [comment]
What values are you talking about?

**Comment by NanoAi** [comment]
Specifically the values listed here. (Specific values for a handful of mods.)
https://github.com/anthxnymc/Spice-of-Life-Apple-Pie/blob/1.20.1/src/main/java/com/tarinoita/solsweetpotato/SOLSweetPotatoConfig.java#L294

But what I'm looking for and am curious about is the ability to have foods scale based on their "quality". Which I believe are calculated here... 
https://github.com/anthxnymc/Spice-of-Life-Apple-Pie/blob/1.20.1/src/main/java/com/tarinoita/solsweetpotato/tracking/FoodList.java#L225

So instead of having the base value be 1 for every food... the better the food, the more contribution it has. This basically gives the ability to automatically calculate diversity for food items added from mods etc.
```
Pufferfish: 0.11
Rotten Flesh: 0.44
Bread: 0.80
Apple: 0.52
Carrot: 0.48
```

**Comment by CreativeMD** [comment]
Using the command /cmdconfig you can define complexity of items as you please. About the auto calculation based of saturation effect is interesting. I will take a look at that and see if I can add something. But my goal is not to copy what another mod does.

**Comment by CreativeMD** [comment]
Ok, added it in the newest version. The diversity is calculated around bread, which has a diversity of `1`. There are also new configuration options to tweak the system. Would be cool if you can try it out and tell me what you think about it.

**Comment by CreativeMD** [comment]
Will close this issue for now. If you have any feedback just post it here (or open a new issue).
